version: '3.8'
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"      # MQTT port
      - "8083:8083"      # MQTT/WebSocket port
      - "8084:8084"      # MQTT/WSS port
      - "8883:8883"      # MQTT/SSL port
      - "18083:18083"    # Dashboard port
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.io
      - EMQX_DASHBOARD__AUTH__USER_ID=admin
      - EMQX_DASHBOARD__AUTH__PASSWORD=public
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    restart: always
  httpd:
    image: httpd:latest
    container_name: httpd
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/local/apache2/htdocs
    restart: always
